### ISSUE TITLE
Make Developer Built .apk's Available on Github?

### ISSUE THREAD

**Issue by DiagonalArg** [arnowelzel/periodical#106]
I wonder if the team might consider making .apk's available here on github.  A number of us run GrapheneOS with [Obtainium](https://github.com/ImranR98/Obtainium).  That allows us to use developer signed packages directly from github or other developer websites, which is preferable to those signed by f-droid.

**Comment by DiagonalArg** [comment]
Great!  Thank you for considering it.  I had missed the web page, but I can get it there; though setting up the Obtainium profile to specifically scrape the version number as an indicator of a new release, is some effort and a little fragile.  Github, on the other hand, is built-in.

**Comment by arnowelzel** [comment]
I added the package for release 1.75 and the next update will also get a release including a binary package.
