### ISSUE TITLE
Set end of period

### ISSUE THREAD

**Issue by mirjamknook** [arnowelzel/periodical#17]
Hello,

Is it possible to end the menstruation period. While clicking on the calendar, cause it seems I only can start a period for the first entry. and other entries. 

With friendly regards,

Mir.

**Comment by arnowelzel** [comment]
Thanks for the suggestion - I'll try to add this for the next update (along with the possibility to take notes for single days as well)

**Comment by arnowelzel** [comment]
BTW: This is a duplicate if #4 ;-)

**Comment by singpolyma** [comment]
Has there been any work on this? These two things are my fiancée's big desires from this app

**Comment by arnowelzel** [comment]
Sorry, I've been quite busy the last months with other projects and my marriage ;-). I'm working on this and will try to release an update in September 2015.

**Comment by singpolyma** [comment]
No problem at all. Thanks for your work, and congrats!

**Comment by arnowelzel** [comment]
Sorry for the really very long delay - other things in my life where more important. However, now there is finally a version 1.0 on it's way with this feature (and others) added.

**Comment by mishabess** [comment]
Thanks for this great app! I'm also interested in having different length of periods -- not a standard length. Thanks, again! - M

**Comment by arnowelzel** [comment]
Thanks for the positive feedback :-). The new release should be available within the next couple of days (as soon as I have finished the screenshots and update descriptions for Google Play etc.).
