### ISSUE TITLE
[feature] Add more infos saved on the calendar

### ISSUE THREAD

**Issue by DarckCrystale** [arnowelzel/periodical#18]
Hello, 

I'm using your app (it's great btw) and I wondered if you could add some other labels which could be set by typing on a date.
_e.G._ Tap on 7 april > Opening of a list (mark as period started, mark as painful,...) > Tap on an item in the list > The day is marked. 

You also could add way to create our own labels.

Thx for your time!

**Comment by arnowelzel** [comment]
Yes, that makes sense and I was also thinking about adding some feature like this. I just don't have so much time at the moment as I'm about to move to Berlin next week ;-).

**Comment by arnowelzel** [comment]
Finally! A new release 1.0 is on it's way with this enhancement and some others :-).
