### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by PanderMusubi** [arnowelzel/periodical#22]
Please add this translation to Dutch http://pastebin.com/4hWVFrKg

Contact me for more translations for this app.

**Comment by arnowelzel** [comment]
Thank you for the translation. However there are other parts to translate as well (see assets/en/... and the content for the Google Play entry in publish/text/...). Can you create a fork and add the translated versions there (main/res/nl/strings.xml, assets/nl/..., publish/text/description-nl-short.txt)? Thank you!

**Comment by PanderMusubi** [comment]
See https://github.com/arnowelzel/periodical/pull/25
