### ISSUE TITLE
Dialog disappears on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [arnowelzel/periodical#30]
When i perform these sequences of events, the dialog on screen disappears:

Sequence 1:
1. Click on day item in calendar
2. Orientation change

Sequence 2-3:
1. Click on ...
2. Click on:
a. Restore
b. Backup
3. Orientation Change

**Comment by arnowelzel** [comment]
Closed with c0fbe2abf8ca3aaecf223cfa32dc1325b6ea0615
