### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [arnowelzel/periodical#40]
Hi @arnowelzel 

I found [this app](https://play.google.com/store/apps/details?id=swagselfie.android.periodical) on the Google Play Store. This guy just took your source code, added some ads in it and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove this copy from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under GNU GPL v3 license and this guy is violating it;
* He is falsely claiming he made the app;
* Provide some screenshots of your own app.

**Comment by arnowelzel** [comment]
Thanks - I'll take care of this and publish the results here.

**Comment by arnowelzel** [comment]
Update:

I contacted the guy - he did not respond yet. But as a reaction(?) to my first e-mail where I told him, that his app is a GPL violation he first added the whole original description from my app including the links to my website etc..

Now I also wrote Google about this case and I wrote him again that his change makes the situation even worse as I was now in the situation that there is Google Play entry telling that this specific app "PERIOD TRACKER" published by me - which is wrong. And again no sources of course. I told him, that I contacted Google and also my laywer - just in case, it is needed.

Then I also found out, that the app logo was obiously copied from the website of [Boots UK](http://www.boots.com/womenshealth/period-delay-clinic) and the Google Play entry indicates that the app uses Ads - which is a violation of the legal terms of Boots - they do not allow to use their content for commercial purposes. So I also contacted Boots and made clear that I am not responsible for this illegal copy. That's the reason, why I am now also in contact with my laywer to avoid any legal problems.

And now the store entry is still there but changed to the title "not published" written in Dutch. At least the app is not listed in Google Play searches or in the [overview of his published apps](https://play.google.com/store/apps/developer?id=Swag+Selfie).

**Comment by arnowelzel** [comment]
Just a final update: Google told me, they will remove the store entry and the app itself is no longer available in its original form.

**Comment by Poussinou** [comment]
Hum, we have a very special case here o_O
It looks like his [developer page](https://play.google.com/store/apps/developer?id=Swag+Selfie) is down, but not the [app](https://play.google.com/store/apps/details?id=swagselfie.android.periodical)...

Anyway, thanks for taking action 👍

**Comment by Poussinou** [comment]
@arnowelzel There is another one here : https://play.google.com/store/apps/details?id=com.droidfactory.periodtracker.menstrual.calendar with ads and IAP...

**Comment by arnowelzel** [comment]
Thanks for pointing this out - I'll take care of it.

**Comment by arnowelzel** [comment]
It took a while, but Google respondend and will delete the app.

Also see here: https://arnowelzel.de/en/again-in-illegal-copy-of-periodical
