### ISSUE TITLE
New Icon?

### ISSUE THREAD

**Issue by DavidXochipilli** [arnowelzel/periodical#41]
Thanks for your awesome app @arnowelzel! 👍
Are you interested in a new app icon? Any ideas?

**Comment by arnowelzel** [comment]
No, so far I did not think about a new icon. But if you have good ideas, just show them.

**Comment by DavidXochipilli** [comment]
I'm trying to play with the concept of leaves or flowers because of the fertility concept.

You can check the animations and different versions of masks here:
[Icon 1](https://adapticon.tooo.io/#/bg=https://i.imgur.com/KjuxyS5.png/fg=https://i.imgur.com/BA5Iu6P.png)
[Icon 2](https://adapticon.tooo.io/#/bg=https://i.imgur.com/flZ10WT.png/fg=https://i.imgur.com/jQH55uf.png)

**Comment by arnowelzel** [comment]
Thanks for the drafts!

However, I'm not sure yet, if this is really the direction I want to go - as the fertility is not the major aspect in Periodical and many other apps also use this "floral" theme already ("Clue", "Period Tracker", "Period Calenmder", "WomanLog", "Ovulation Tracker", "Menstrual Diary" and so on...). That's the reason why I use the blood drop and not a flower (or any other "cute" image like feathers, birds, little girls etc.).

**Comment by gaellericher** [comment]
I was glad to find an app without flower and pink (and open source as well). I had some ideas coming across this thread for a logo expanding on the blood drop representation: one with a subtle vulva (maybe inappropriate) and the other with a simple calendar. I am not a designer, so these are merely ideas but they should be simple enough to "implement" if ever a more modern logo was desired. 
![periodical](https://user-images.githubusercontent.com/7461447/40627826-88a20418-62c1-11e8-9875-533c5baf8e1c.png)

**Comment by arnowelzel** [comment]
@gaellericher Thanks for the ideas - I like the idea of combining a calendar symbol with the blood drop, but the subtle vulva is also ok and subtle enough not to be too offending I think.

**Comment by DavidXochipilli** [comment]
https://adapticon.tooo.io/#/bg=https://i.imgur.com/qa93xhI.png/fg=https://i.imgur.com/bPucIpg.png

I'm trying a few concepts right now, which I'll be sending you in the next few days.
In the meantime here's a simple icon with a drop so you can check animations and colors if you want to.

**Comment by arnowelzel** [comment]
@DavidXochipilli thanks for the new icon. I'd prefer a more "red" version as in the original icon. Your current draft is more pink than red. But otherwise this looks promising.

**Comment by arnowelzel** [comment]
@DavidXochipilli Thank you! Looks nice. Can you create a pull request with the updated resources?

@gaellericher what do you think?

**Comment by DavidXochipilli** [comment]
I will create a PR soon. But I will enable edits from maintainers so that you can make changes @arnowelzel. I am not deep into coding and I might do stupid things. 😅 

Additionally, I attached the icon here. It is licensed under the CC0 1.0 Universal license and credits go to [@kevttob](https://plus.google.com/101300967614699398374) if you like.

[periodical.zip](https://github.com/arnowelzel/periodical/files/2189959/periodical.zip)

**Comment by arnowelzel** [comment]
Sorry if I sound rude: I just showed this to my wife and her first association was "why is the icon looking like an baking oven". I have to think about.

**Comment by DavidXochipilli** [comment]
OK, no problem. 
I did a little research about implementing the adaptive icon and did not understand much. So it would be great if you could do the implementation yourself in the case that you wish to change the icon.

**Comment by SenaidaHdez** [comment]
I liked the first and the third logo proposed by @gaellericher

**Comment by avtkal** [comment]
I do think it would be great to have a new icon ☺️ I actually like the second and third logos made by @gaellericher.

**Comment by arnowelzel** [comment]
@avtkal do you refer to this?

![grafik](https://user-images.githubusercontent.com/6613614/111814451-c2f4c000-88da-11eb-958f-63f5a1c4e565.png)

**Comment by avtkal** [comment]
@arnowelzel Yep, that's it!

**Comment by arnowelzel** [comment]
@gaellericher It's been a while - but as there are multiple votes for your draft I'd like to use it - personally I'd prefer the middle one. Can you provide a SVG version of this? If not, I'll try to create that on my own based on the image.

**Comment by gaellericher** [comment]
@arnowelzel Sorry, it's been a while. I could not find the file and recreated several versions from the shape of the second one.  
![image](https://user-images.githubusercontent.com/7461447/127491249-ad271773-7857-4e3b-9bd0-0b9acd3a8725.png)

Please find an SVG file here: [periodical.zip](https://github.com/arnowelzel/periodical/files/6900439/periodical.zip)

**Comment by arnowelzel** [comment]
> @arnowelzel Sorry, it's been a while. I could not find the file and recreated several versions from the shape of the second one.
> ![image](https://user-images.githubusercontent.com/7461447/127491249-ad271773-7857-4e3b-9bd0-0b9acd3a8725.png)
> 
> Please find an SVG file here: [periodical.zip](https://github.com/arnowelzel/periodical/files/6900439/periodical.zip)

Thank you for your help! I'll try to add this as the new application icon as soon as possible. However at the moment I am quite occupied with other projects, so it may take a few weeks.

**Comment by idotj** [comment]
The new icon got merged :)
Just in case, I publish here the SVG version:

![periodical_logo](https://github.com/arnowelzel/periodical/assets/6554216/df0a5212-34dd-4630-8bd3-f3efd4165ff6)

**Comment by arnowelzel** [comment]
The icon is now published, thanks for your help and sorry for the long delay!

**Comment by idotj** [comment]
Great, thanks also to @gaellericher for her work with the logo!
Thanks
