### ISSUE TITLE
Improve translations using Crowdin

### ISSUE THREAD

**Issue by arnowelzel** [arnowelzel/periodical#46]
In the past @PanderMusubi @swmail @larjona @valerio-bozzolan @naofum @JuliaJ999 @NeoFrontier-Technologies @I-Spangler @Primokorn and others contributed translations - thank you!

However, after a couple of updates some translations got outdated and some new strings got added. I did some of the updates myself using dictionaries - which is not the ideal solution and in fact all translations except German should be checked for correctness.

To make the whole process a lot easier, I created a project on Crowdin, which is also used by other Open Source projects like [KeePass2Android](https://github.com/PhilippC/keepass2android).

If you want to join, use the following URL (you can sign in there with your Github account as well): https://crwd.in/periodical

**Comment by PanderMusubi** [comment]
Improved Dutch translation.

**Comment by arnowelzel** [comment]
@PanderMusubi did you update the translation on Crowdin?

**Comment by PanderMusubi** [comment]
Yes
