### ISSUE TITLE
Go directly to the details doesn't stick

### ISSUE THREAD

**Issue by Primokorn** [arnowelzel/periodical#49]
Hi,

Steps to reproduce:
1. Open the drawer
2. Select `Settings`
3. Check `Go directly to the details`
4. Close the app
5. Return to the settings. The option is unchecked.

Device: OnePlus 3T
Android Oreo 8.1
App version: 1.13 (F-Droid)

**Comment by arnowelzel** [comment]
I already found the reason:

Periodical keeps a copy of all app preferences in its local database - however, the preference entries are only stored to the database when returning from the preference activity back to the main activitiy with the calendar view. When the app is closed while the preferences are still open, the database does not get updated.

I'll fix this with the next update.

**Comment by arnowelzel** [comment]
Fixed with https://github.com/arnowelzel/periodical/commit/5b7dd73af2b98754316f1b4f8c9ce756df4e32e3. The preferences activity will now store every option immediately when changing it in the GUI.
