### ISSUE TITLE
german translation disappeared

### ISSUE THREAD

**Issue by HieronymusCH** [arnowelzel/periodical#52]
Periodical doesn't show in the german translation anymore.
Android Settings are set to "Deutsch (Schweiz)".

Periodical 1.16

Fairphone2
Android 6.0.1

**Comment by arnowelzel** [comment]
I believe this may have to do with the transition to Crowdin, which generates localization with region specific language codes - so "Deutsch" and "Deutsch (Schweiz)" will be handled different.

I'll fix this as soon as possible.

**Comment by HieronymusCH** [comment]
It is fixed. Thank you \o/
