### ISSUE TITLE
Intercourse icon in calendar view

### ISSUE THREAD

**Issue by SenaidaHdez** [arnowelzel/periodical#54]
I think an intercourse icon in the calendar view would make a lot of sense. Either if you are evaluating risk or the luck of getting pregnant, it is something that would make a lot easier to track your sex activity during the months.

**Comment by arnowelzel** [comment]
Any suggestion which symbol to use for this in the calender view? (BTW: you know, that you can already mark "intercourse" in the details and also see that in the detailed list?)

**Comment by Mystro256** [comment]
I'd suggest a heart for intercourse and a star if any notes are present. I would put them in a location not obscured by the intensity dots, blood drop, or ovulation O, so they can be seen easily.

**Comment by arnowelzel** [comment]
I'll add something like this in the next update within the next 1-2 weeks. Sorry for the delay.

**Comment by Mystro256** [comment]
No worries, I actually took a look and made something this morning. I'll make a pull request.

**Comment by arnowelzel** [comment]
It took a while, but now it's finally implemented with release 1.30. I also added another indicator for notes and symptoms in the calendar and change some other things.
