### ISSUE TITLE
Averge period length is not updated in Android 8.0.0

### ISSUE THREAD

**Issue by SirJane** [arnowelzel/periodical#58]
Though I entered more period series with differing lengths, the average value shown at the top right seems to be stuck with the first that I entered. Min/max is correct so far.

I haven't updated to higher 8.x versions of Android. It worked fine with CM14.1.

**Comment by arnowelzel** [comment]
Sorry, I can't reproduce this behaviour with Android 8 or 9 and I also don't have any idea, why the calculation within the app should be dependent on the Android version.

My quick test:

Perdiod start at 2019-01-01
Perdiod start at 2019-01-28 -> 27 days
Perdiod start at 2019-02-25 -> 28 days
Perdiod start at 2019-03-20 -> 23 days

Calculated minimum: 23 days
Calculated maximum: 28 days
Calculated average: 26 days

The code in the app is always the same for every Android version. Can you provide a copy of the database backup so I can check the database if there are any problems with it? You will find my e-mail address on my website: https://arnowelzel.de/en/about-me

**Comment by arnowelzel** [comment]
Closed, sinced the problem can not be reproduced.
