### ISSUE TITLE
Later than calculated bleeding start dates cause issues

### ISSUE THREAD

**Issue by DPTJKKVH** [arnowelzel/periodical#63]
Android 9
Periodical 1.41

Lets assume the calculated start date is the 10th day of May. If my periode starts one day early I can mark the 9th of May and the tracker will move the end date accordingly. If my periode starts at the calculated date everything works out fine as well.

However if my periode starts one or two days after the calculated start date, the tracker gets confused:

If I mark the 12th of May as the start of my periode then the tracker will enforce the calculated start date (10th of May) and set my actual start date as the end date.

I hope my explanation is not too confusing. I can provide some pictures later if required.

**Comment by arnowelzel** [comment]
I can reproduce this bug here. Sorry for the confusion - it looks like the last updated introduced this behaviour. I'll fix this as soon as possible.

**Comment by DPTJKKVH** [comment]
Thanks for your quick reply. I'm looking forward to the fixed version.

Also thanks for creating and maintaining this free and open source app. Menstruation is a very personal matter and I'm grateful to have an offline app that doesn't collect my data.

**Comment by arnowelzel** [comment]
I just fixed this bug and pushed a new version to Google Play. F-Droid will follow as soon as they updated their repository.

**Comment by DPTJKKVH** [comment]
Yay! Thanks for the quick fix. I will test it as soon as it's up on F-Droid. If you won't hear back from me it means everything is fine. :)

**Comment by jacksgt** [comment]
I also just had this issue - thank you for the super quick fix!
