### ISSUE TITLE
Add export/import to/from csv

### ISSUE THREAD

**Issue by 2e8** [arnowelzel/periodical#64]
Would it be possible to add export of data to csv and import from csv?

**Comment by arnowelzel** [comment]
Please explain the use case - when exactly do you need to import data from CSV to Periodical?

A complication is, that the data is not just a list of entries, but consists of three separate tables:

- calendar data (period start, days of the period)
- optional day specific symptoms (variable number), n:1 relation to calendar data
- optional day specific notes (any kind of text), 1:1 relation to calendar data

**Comment by 2e8** [comment]
Use case import: I have collected data during last 10 years and would like to keep it in one place. If I switch to periodical, I would like to import my data. Easiest exchange format would be csv (table in plain text).

Use case export: I'm collecting also other data (steps, blood pressure, etc.) and would like to compare them also with data, stored in periodical.

I see 2 possibilities to map csv to your db structure:
- 3 separate csv files: Just put in both "optional" files "date" from main table instead of "record id". (I'm not sure about exact db structure)
- 1 csv file: 1 record per day. In addition to main table, every symptom in separate column. Notes also in separate column.

I would prefer second solution. It's easier for manual changes.

**Comment by arnowelzel** [comment]
Meanwhile the backup was change to use JSON - so this may be an alternative.
