### ISSUE TITLE
[Feature request] Custom path for backup/restore

### ISSUE THREAD

**Issue by Mageti** [arnowelzel/periodical#71]
Hello,
Thank you for this wonderful app I use for years.
May I suggest a new feature ?
I think it would be great to be able to backup the db to a custom path, and restore from a custom path.

Context: I run a nextcloud server, and I backup some folders from the phone on it. I use [folder sync](https://play.google.com/store/apps/details?id=dk.tacit.android.foldersync.lite) to mirror them between the phone and the server (think of it like permanent _rsync_).
My use case would be this one:
- Use periodical on a phone
- save/export the db to a custom path that is synced with my nextcloud server
- change phone, without using google backup/restore (or phone hard reset because of OS failure)
- re-sync folder on phone in the other way
- restore the db from the synced folder

Additional optional feature would be to export the db to said custom path on every change, but that'd be the cherry on the cake.

Thanks in advance

**Comment by arnowelzel** [comment]
I have to change the way how the backup is done for Android 11 and up anyway to use the storage access framework. As part of these changes I can also add a custom location for backups.

BTW: I also use Nextcloud and DAVx5 and Foldersync to keep backups of my device ;-)

**Comment by arnowelzel** [comment]
Closed with 652dae8bf4a3331718f9c73101842b602b69086e
