### ISSUE TITLE
Backup restore failed

### ISSUE THREAD

**Issue by R4U5CH1337** [arnowelzel/periodical#77]
I'm not able to restore my main.db file in de.arnowelzel.android.periodical.
The app has the right to access storage but after "restore" I need to allow it before select the file anyhow. In the end it's not working. 
System: Pixel 3a, LOS 17.1 + GApps pico

**Comment by R4U5CH1337** [comment]
Found it: need to do a backup after fresh install (no entry), after I need to overwrite that "backup" main.db with my real backup main.db inside the folder and do a restore. Good to know.

**Comment by arnowelzel** [comment]
Thanks for the info - maybe I'll add this as a hint in the help text.
