### ISSUE TITLE
abandoned?

### ISSUE THREAD

**Issue by andsofine** [arnowelzel/periodical#87]
no updates for a long time, the app is abandoned?

**Comment by arnowelzel** [comment]
No, the app is not abandoned - but I have just no time for updates at the moment.

Help is always welcome!

**Comment by andsofine** [comment]
> No, the app is not abandoned - but I have just no time for updates at the moment.
> 
> Help is always welcome!

this is great news. unfortunately, I'm not a coding expert, so I can't really help.

**Comment by Kirk1984** [comment]
Why Fork drip when periodical is working fine? And if he has no time for updates, where would he find the time to fork another app that does what periodical already does? Drip just isn't updated on fdroid.

My wife uses periodical for years now and it is just working fine.

**Comment by arnowelzel** [comment]
Just a little update:

I plan to imlement some of the open issues in the near future (which means within the next weeks):

- Optional password protection (#86)
- Easier backup and restore to another smartphone by using a universal backup format and not just copying the internal database files (#88)

And as always: help with any of the open issues is very welcome! Feel free to participate and send your pull requests. The idea of open source is not only to have software for free but also to collaborate - thank you!

**Comment by arnowelzel** [comment]
> > No, the app is not abandoned - but I have just no time for updates at the moment.
> > Help is always welcome!
> 
> but I can suggest making a fork of the "drip". It doesn't seem to be very updated. but there is already some progress. you can get the latest version from gitlab. what do you think?

If you want to use Drip - just use it. There is not need to fork it.

**Comment by arnowelzel** [comment]
If anyone wants to participate Drip to make it to a more competetive App - feel free to do so: https://gitlab.com/bloodyhealth/drip

If you want to have features from Drip in Periodical - freel free to create an issue where you describe the features.

However I won't give up Periodical because of this - there are already thousands of active users and translations in more than 20 languages (see https://crwd.in/periodical) and Drip is a completely different approach using ReactJS and a HTML based UI. I also don't have a mac or iPhone to do any of the iOS stuff.

**Comment by Kirk1984** [comment]
Drip also doesn't look like its not being worked on.

**Comment by arnowelzel** [comment]
> Drip also doesn't look like its not being worked on.

Well - the last changes in the Drop repository are 2 days old. This does not look like "not being worked on" to me.

And even if no substantial changes happen this does not mean that no one can participate. Did you ask the team, if they would publish an update if someone implements new features or completes the iOS version? I doubt that they would refuse any help.

Sorry to be so blunt: but complaining about the fact that someone does not continue to work on a project for free which is open source and free to use helps nobody. If you want projects like Drip or Periodical to go on and become more competetive, either help with development or try to find someone who can help. You can also start a crowdfunding campaign to get people paid to work on these projects. We all need to earn our money for living and I can only spare my free time here, sorry.

**Comment by arnowelzel** [comment]
Ok, my final comment in this matter:

No, Periodical is not abandoned, I just don't have time to provide an update multiple times a year or every month but there will be updates. Any help is welcome!

No, I will also not give up Periodical and continue to work on another project instead - there are already many users of Periodical and many contributors who did translations etc..

If you want to see any of the features of Drip in Periodical as well you need to specify which features exactly. Create an issue for each feature you would like to see.
