### ISSUE TITLE
Improve backup/restore

### ISSUE THREAD

**Issue by arnowelzel** [arnowelzel/periodical#88]
Backup will just copy the existing SQLite files to a backup location and restore will try to restore these files and open the database again.

However when transferring the app to another device, this method may not work very well. Therefore we need a more universal approach, where the data is serialized to an exchange format including version information using JSON. This way it will be much easier to restore data on another device.

**Comment by audeb44** [comment]
I just come here because I have a problem with back up and restore, to say it in case  you want to continue with this issue..

**Comment by arnowelzel** [comment]
Thanks, yes I'll have to continue to work on this. Sorry for the delay.

What often works: make a backup on the **new** device first and then copy over the files from the old device into the folder of the new device. Then try to restore that data.

Anyway - I try to implement something more robust as soon as possible.

**Comment by audeb44** [comment]
Thanks a lot for your answer!! What you propose seems rare to me but I will try it a little bit later.

**Comment by arnowelzel** [comment]
This feature was implemented for 1.73.
