### ISSUE TITLE
"Edit Calendar Entry" displays wrong date

### ISSUE THREAD

**Issue by erryr** [arnowelzel/periodical#95]
I am unable to edit May 5 and May 6th's calendar data. When I go to "edit details," on May 5, I'm taken to the calendar data from April 5. And the same happens with May 6's calendar data taking me to April 6. This month-jump doesn't happen on nearby dates like May 3, 4, 7, 8, etc., but I haven't input data into those days.

However, when I go back to April and try to edit any April dates with calendar data, I'm taken to that date's page for March (March 3 instead of April 3, for example.) This happens for every previous month. Jumping forward to June, those data pages for individual days show up correctly as June.

**Comment by arnowelzel** [comment]
I tried to reproduce this - but this does not happen on any of my devices and neither in my test enviroment.x

See the screenshots - I open May, then tap on May 5 and the details are opened as expected. Also when I change the start of the week from Sunday to Monday it still works as expected.

So I don't know what to do - without a reproducable error it is hard to fix anything.

<img src="https://user-images.githubusercontent.com/6613614/236671485-d3193660-91a7-49f9-9f66-68bd4fc182ad.png" width="250" />

<img src="https://user-images.githubusercontent.com/6613614/236671503-f900ae81-3e31-4d35-8fd5-53f5f13b8185.png" width="250" />

<img src="https://user-images.githubusercontent.com/6613614/236671638-18311d9d-26e3-4b89-93ef-ff0f97c70be5.png" width="250" />

**Comment by arnowelzel** [comment]
Update: I identified the issue and will provide a fix as soon as possible. Sorry for the confusion.

**Comment by arnowelzel** [comment]
Fixed with https://github.com/arnowelzel/periodical/commit/9a0bee6e90dfaa3e4c8a49bc6185f2aa49ab1b63

**Comment by Weishaupt** [comment]
https://github.com/arnowelzel/periodical/assets/2642714/1812f775-e210-4c29-a34c-de7d0377b37b

The date is correct.
